### ISSUE TITLE
baichuan13B load error

### ISSUE THREAD

**Issue by leiwen83** [ModelTC/lightllm#106]
Hi,

I try use lightllm with baichuan13B model, but get below error. I cannot find any TrainingArguments in the code, so is there anything else need to be configured?...

The launch command is as:
```
python -m lightllm.server.api_server --trust_remote_code --model_dir  /xxxx/  --host 0.0.0.0 --port 8000 --tp 2
```

Error log:
```
load model error: Can't get attribute 'TrainingArguments' on <module 'lightllm.server.api_server' from '/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/api_server.py'> Can't get attribute 'TrainingArguments' on <module 'lightllm.server.api_server' from '/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/api_server.py'> <class 'AttributeError'>
################
load model error: Can't get attribute 'TrainingArguments' on <module 'lightllm.server.api_server' from '/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/api_server.py'> Can't get attribute 'TrainingArguments' on <module 'lightllm.server.api_server' from '/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/api_server.py'> <class 'AttributeError'>
router init state: Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 257, in start_router_process
    asyncio.run(router.wait_to_model_ready())

  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete

  File "/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 62, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)

  File "/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 211, in init_model
    await ans

  File "/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 189, in _func
    return ans.value

  File "/usr/local/lib/python3.10/dist-packages/rpyc-5.3.1-py3.10.egg/rpyc/core/async_.py", line 108, in value
    raise self._obj

_get_exception_class.<locals>.Derived: Can't get attribute 'TrainingArguments' on <module 'lightllm.server.api_server' from '/usr/local/lib/python3.10/dist-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/api_server.py'>```

**Comment by leiwen83** [comment]
it could be fixed by below change:

```
diff --git a/lightllm/common/basemodel/layer_weights/hf_load_utils.py b/lightllm/common/basemodel/layer_weights/hf_load_utils.py
index 30be3a5..d9ef3ad 100644
--- a/lightllm/common/basemodel/layer_weights/hf_load_utils.py
+++ b/lightllm/common/basemodel/layer_weights/hf_load_utils.py
@@ -15,7 +15,8 @@ def load_hf_weights(data_type, weight_dir, pre_post_layer=None, transformer_laye
     candidate_files = list(filter(lambda x : x.endswith('.safetensors'), files))
     if len(candidate_files) == 0:
         use_safetensors = False
-        candidate_files = list(filter(lambda x : x.endswith('.bin'), files))
+        candidate_files = list(filter(lambda x : x.endswith('.bin') and not x.endswith("training_args.bin"), files))
```
