### ISSUE TITLE
加载自己基于chatglm训练的模型时报错

### ISSUE THREAD

**Issue by UncleFB** [ModelTC/lightllm#111]
################
load model error: 'ffn_hidden_size' 'ffn_hidden_size' <class 'KeyError'>
Process Process-1:
Traceback (most recent call last):
  File "/lightllm/lightllm/server/router/manager.py", line 257, in start_router_process
    asyncio.run(router.wait_to_model_ready())
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/lightllm/lightllm/server/router/manager.py", line 62, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)
  File "/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 209, in init_model
    ans : rpyc.AsyncResult = self._init_model(rank_id, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 77, in exposed_init_model
    raise e
  File "/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 69, in exposed_init_model
    self.model = ChatGlm2TpPartModel(rank_id, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/lightllm/lightllm/models/chatglm2/model.py", line 23, in __init__
    super().__init__(tp_rank, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/lightllm/lightllm/models/llama2/model.py", line 20, in __init__
    super().__init__(tp_rank, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/lightllm/lightllm/models/llama/model.py", line 30, in __init__
    super().__init__(tp_rank, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/lightllm/lightllm/common/basemodel/basemodel.py", line 37, in __init__
    self._init_weights()
  File "/lightllm/lightllm/common/basemodel/basemodel.py", line 70, in _init_weights
    load_hf_weights(
  File "/lightllm/lightllm/common/basemodel/layer_weights/hf_load_utils.py", line 30, in load_hf_weights
    layer.load_hf_weights(weights)
  File "/lightllm/lightllm/models/llama/layer_weights/transformer_layer_weight.py", line 14, in load_hf_weights
    self._load_ffn_weights(weights)
  File "/lightllm/lightllm/models/chatglm2/layer_weights/transformer_layer_weight.py", line 70, in _load_ffn_weights
    intermediate_size =self.network_config_['ffn_hidden_size'] * 2
KeyError: 'ffn_hidden_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lightllm/lightllm/server/router/manager.py", line 260, in start_router_process
    err_str = '\n'.join(traceback.format_exception(e))
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

**Comment by hiworldwzj** [comment]
@UncleFB 你自己的 config.json 里面估计和标准的config.json 关于ffn的层的配置存在问题。你检查一下修改到一致把。

**Comment by UncleFB** [comment]
自己的模型是chatglm-6b，并不是chatglm2-6b

**Comment by UncleFB** [comment]
自己的模型是chatglm-6b，并不是chatglm2-6b
