### ISSUE TITLE
[BUG] /v1/chat/completions  interface problem

### ISSUE THREAD

**Issue by chengshenlian** [ModelTC/lightllm#126]
**环境配置：**
操作系统：Ubuntu 20.04.2 LTS Server 版本
Python 版本：3.9 (通过conda安装)
CUDA 版本：11.7 (注意，这不是推荐的11.8版本)
torch版本: 2.0
单张显卡: RTX 3090 24GB

一丶/generate接口测试正常
安装requirements.txt中的依赖后，我运行了以下命令，一切正常，/generate接口也能正常响应：
```shell
python -m lightllm.server.api_server --model_dir /path/llama-7B --host 0.0.0.0 --port 8080 --tp 1 --max_total_token_num 1500 --tokenizer_mode fast
```
二丶/v1/chat/completions 提示安装fschat[model_worker,webui]

在尝试构造请求以调用/v1/chat/completions接口时，系统提示我需要安装fschat[model_worker,webui]。触发错误代码如下：
```python
raise ModuleNotFoundError(
    "fastchat is not installed. Please install fastchat to use "
    "the chat completion and conversation APIs: `$ pip install 'fschat[model_worker,webui]'`"
)

```
三丶安装fschat[model_worker,webui]后重启报错
安装上述依赖后，我再次运行了相同的命令，但这次遇到了一个错误。错误消息如下：
```python
$ python -m lightllm.server.api_server --model_dir /path/llama-7B --host 0.0.0.0 --port 8080 --tp 1 --max_total_token_num 1500 --tokenizer_mode fast

For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Process Process-1:
For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Traceback (most recent call last):
  File "/data/gitclone/lightllm/lightllm/server/router/manager.py", line 257, in start_router_process
    asyncio.run(router.wait_to_model_ready())
  File "/root/anaconda3/envs/light/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/data/gitclone/lightllm/lightllm/server/router/manager.py", line 62, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)
  File "/data/gitclone/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 209, in init_model
    ans : rpyc.AsyncResult = self._init_model(rank_id, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/data/gitclone/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 42, in exposed_init_model
    torch.cuda.set_device(rank_id)
  File "/root/anaconda3/envs/light/lib/python3.9/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
  File "/root/anaconda3/envs/light/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/light/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/light/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/gitclone/lightllm/lightllm/server/router/manager.py", line 260, in start_router_process
    err_str = '\n'.join(traceback.format_exception(e))
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

```
猜测：
1. 我怀疑这个问题可能是由于CUDA版本不匹配或依赖不兼容造成的。
2. 我想知道是否有其他人在尝试使用/v1/chat/completions接口时遇到了类似的问题？

**Comment by hiworldwzj** [comment]
@chengshenlian 这个CUDA的错误以前遇到过，大多都是在多卡场景下，每个推理进程需要设置自己单独使用的显卡之前，有其他使用显卡的操作，就会导致类似的错误。可能是 fschat 的这个包是不是内部有自己使用显卡的操作，这个我们会定位一下问题原因。

**Comment by ChieloNewctle** [comment]
可以试试加入
```python
torch.multiprocessing.set_start_method('spawn', force=True)
```

**Comment by chengshenlian** [comment]
我已找到一个可能的解决方案来解决我之前报告的错误。解决方案涉及对lightllm/server/api_server.py文件进行修改。
在`lightllm/server/api_server.py`文件中，我尝试加入以下代码行：
这个更改能解决我遇到的CUDA初始化问题。
```python
torch.multiprocessing.set_start_method('spawn')
```
![image](https://github.com/ModelTC/lightllm/assets/134602920/2989e240-9112-4f5a-a2bb-d6769221dd75)

**Comment by WANDY666** [comment]
（使用/v1/chat/completions接口时，系统提示需要安装fschat[model_worker,webui]。）
fschat这个包是用来根据输入的model参数，将messages参数构建成不同风格的prompt喂给模型，因此只会在/v1/chat/completions接口中使用。
**为了避免大家下载不必要的包，只会在使用该接口时检查，如果没有fschat则提示安装。**

**Comment by hiworldwzj** [comment]
@ChieloNewctle  @chengshenlian 多谢你们的建议。我们尽快完善，也欢迎PR。
