### ISSUE TITLE
[BUG] Use Llama2 with ptxas fatal   : Value 'sm_89' is not defined for option 'gpu-name'

### ISSUE THREAD

**Issue by Alberoyang** [ModelTC/lightllm#176]
**Before you submit an issue, please search for existing issues to avoid duplicates.**

**Issue description:**

I had already start Llama2 with lightllm, but when I send the request it appears  "Value 'sm_89' is not defined for option 'gpu-name'"

**Steps to reproduce:**

Please list the steps to reproduce the issue, such as:

1. `python -m lightllm.server.api_server --model_dir /mnt/ecs/img-gpu02/models/Chinese-Llama-2-7b --host 0.0.0.0 --port 8701 --tp 1 --max_total_token_num 4096`
2. 
```
import time
import requests
import json

url = 'http://localhost:8701/generate'
headers = {'Content-Type': 'application/json'}
data = {
    'inputs': 'What is AI?',
    "parameters": {
        'do_sample': False,
        'ignore_eos': False,
        'max_new_tokens': 1024,
    }
}
response = requests.post(url, headers=headers, data=json.dumps(data))
if response.status_code == 200:
    print(response.json())
else:
    print('Error:', response.status_code, response.text)
```
3 See error

**Expected behavior:**

see response

**Error logging:**
```
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /data/usr/yuyang/lightllm/lightllm/server/router/manager.py:88> exception=RuntimeError("Internal Triton PTX codegen error: \nptxas fatal   : Value 'sm_89' is not defined for option 'gpu-name'\n")>
Traceback (most recent call last):
  File "<string>", line 21, in _rms_norm_fwd_fused
KeyError: ('2-.-0-.-0-d6e5675c89b63c389326c8b846421ab2-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d492a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'fp32'), (16384,), (True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/usr/yuyang/lightllm/lightllm/server/router/manager.py", line 91, in loop_for_fwd
    await self._step()
  File "/data/usr/yuyang/lightllm/lightllm/server/router/manager.py", line 112, in _step
    await self._prefill_batch(self.running_batch)
  File "/data/usr/yuyang/lightllm/lightllm/server/router/manager.py", line 149, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/data/usr/yuyang/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 241, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/data/usr/yuyang/lightllm/lightllm/utils/infer_utils.py", line 54, in inner_func
    result = func(*args, **kwargs)
  File "/data/usr/yuyang/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 112, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/data/usr/yuyang/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 163, in forward
    logits = self.model.forward(**kwargs)
  File "/data/usr/tools/miniconda/envs/lightllm/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/usr/yuyang/lightllm/lightllm/common/basemodel/basemodel.py", line 128, in forward
    return self._prefill(batch_size, total_token_num, max_len_in_batch, input_ids, b_loc, b_start_loc, b_seq_len)
  File "/data/usr/yuyang/lightllm/lightllm/common/basemodel/basemodel.py", line 152, in _prefill
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/data/usr/yuyang/lightllm/lightllm/common/basemodel/basemodel.py", line 192, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/data/usr/yuyang/lightllm/lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_template.py", line 129, in context_forward
    self._context_attention(input_embdings,
  File "/data/usr/yuyang/lightllm/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/data/usr/yuyang/lightllm/lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_template.py", line 79, in _context_attention
    input1 = self._att_norm(input_embding, infer_state, layer_weight)
  File "/data/usr/yuyang/lightllm/lightllm/models/llama/layer_infer/transformer_layer_infer.py", line 37, in _att_norm
    return rmsnorm_forward(input, weight=layer_weight.att_norm_weight_, eps=self.eps_)
  File "/data/usr/yuyang/lightllm/lightllm/models/llama/triton_kernel/rmsnorm.py", line 59, in rmsnorm_forward
    _rms_norm_fwd_fused[(M,)](x_arg, y, weight,
  File "/data/usr/tools/miniconda/envs/lightllm/lib/python3.10/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 41, in _rms_norm_fwd_fused
  File "/data/usr/tools/miniconda/envs/lightllm/lib/python3.10/site-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/data/usr/tools/miniconda/envs/lightllm/lib/python3.10/site-packages/triton/compiler.py", line 901, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas fatal   : Value 'sm_89' is not defined for option 'gpu-name'
```

**Environment:**

Please provide information about your environment, such as:

- [ ] Using container

- OS: (Ubuntu 22.04.3 LTS)
- GPU info:
  - `nvidia-smi` (`NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0 `)
  - Graphics cards: (4090x2)
- Python: (eCPython3.10.13)
  - currently, only python>=3.9 is supported
- LightLLm: (git commit-hash)
  - for container: `docker run --entrypoint cat --rm ghcr.io/modeltc/lightllm:main /lightllm/.git/refs/heads/main`
- openai-triton: `pip show triton`
`Name: triton
Version: 2.0.0.dev20221202
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/openai/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License: 
Location: /data/usr/tools/miniconda/envs/lightllm/lib/python3.10/site-packages
Requires: cmake, filelock, torch
Required-by: lightllm`

**Language:**

Please use English as much as possible for better communication.

**Comment by hiworldwzj** [comment]
@Alberoyang please use triton 2.1.0,  triton 2.0.0 can not support 4090 now.
