### ISSUE TITLE
triton kernel compile error

### ISSUE THREAD

**Issue by leiwen83** [ModelTC/lightllm#19]
Hi,

When I try to use lightllm serving with llama7B/13B, I met triton compile error.
I use the dockerfile in git to build to test image, and with A100-40G to test.

So am I missing anything to enable the test?

The error log is as:
```
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /opt/lightllm/lightllm/server/router/manager.py:84> exception=CompilationError('at 38:4:\ndef _rotary_kernel(\n    Q, Cos, Sin,\n    stride_qbs, stride_qh, stride_qd,\n    stride_cosbs, stride_cosd,\n    stride_sinbs, stride_sind,\n    max_total_len,\n    H,  # N_CTX 代表要计算的上下文长度\n    BLOCK_HEAD: tl.constexpr,\n    BLOCK_SEQ: tl.constexpr,\n    BLOCK_DMODEL: tl.constexpr,\n):\n    cur_head_index = tl.program_id(0)\n    cur_seq_index = tl.program_id(1)\n\n    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)\n    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)\n\n    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)\n    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)\n\n    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd\n    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd\n\n    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd\n\n    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n\n    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n\n    out0 = q0 * cos - q1 * sin\n    out1 = q0 * sin + q1 * cos\n\n    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n\n    return\n    ^')>
Traceback (most recent call last):
  File "<string>", line 21, in _rotary_kernel
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-2d732a2488b7ed996facc3e641ee56bf-2a292e5784d51bd8ac8bf0d3423dfbd4-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (4, 32, 128), (True, True, True, (True, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (False, False), (False, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 937, in build_triton_ir
    generator.visit(fn.parse())
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/opt/conda/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 183, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/opt/conda/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/opt/conda/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/conda/lib/python3.9/site-packages/triton/compiler.py", line 263, in visit_FunctionDef
    fn.reset_type(self.prototype.to_ir(self.builder))
  File "/opt/conda/lib/python3.9/site-packages/triton/language/core.py", line 301, in to_ir
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
  File "/opt/conda/lib/python3.9/site-packages/triton/language/core.py", line 301, in <listcomp>
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
AttributeError: 'NoneType' object has no attribute 'to_ir'

```

**Comment by hiworldwzj** [comment]
@leiwen83 Hello， You can first check if your Triton version is okay. Then I have encountered a similar error before, and the cause was either incomplete download of the llama weights or the weight's name not matching the standard format precisely.

**Comment by leiwen83** [comment]
@hiworldwzj Do you have suggest llama weight? I try several from hugginface, but same issue raise.
The triton version is used suggested in the requirement.txt

**Comment by hiworldwzj** [comment]
@leiwen83 Hello,  I encountered this error before because the .bin file in the weights was missing one.  can you check it ? the llama weights from hugging face should be ok.  you can also use code 
~~~python
bin_path = "**.bin"
weights = torch.load(bin_path , 'cpu')
for name, _ in weights.items():
    print(name)
~~~ 
to load and print weights name. send the weights name to me, I will check if the weights name is ok.

**Comment by leiwen83** [comment]
here is weight name of pytorch_model-00001-of-00002.bin of llama 7b from https://huggingface.co/jeffwan/llama-7b-hf

```
model.embed_tokens.weight
model.layers.0.self_attn.q_proj.weight
model.layers.0.self_attn.k_proj.weight
model.layers.0.self_attn.v_proj.weight
model.layers.0.self_attn.o_proj.weight
model.layers.0.self_attn.rotary_emb.inv_freq
model.layers.0.mlp.gate_proj.weight
model.layers.0.mlp.down_proj.weight
model.layers.0.mlp.up_proj.weight
model.layers.0.input_layernorm.weight
model.layers.0.post_attention_layernorm.weight
model.layers.1.self_attn.q_proj.weight
model.layers.1.self_attn.k_proj.weight
model.layers.1.self_attn.v_proj.weight
model.layers.1.self_attn.o_proj.weight
model.layers.1.self_attn.rotary_emb.inv_freq
model.layers.1.mlp.gate_proj.weight
model.layers.1.mlp.down_proj.weight
model.layers.1.mlp.up_proj.weight
model.layers.1.input_layernorm.weight
model.layers.1.post_attention_layernorm.weight
model.layers.2.self_attn.q_proj.weight
model.layers.2.self_attn.k_proj.weight
model.layers.2.self_attn.v_proj.weight
model.layers.2.self_attn.o_proj.weight
model.layers.2.self_attn.rotary_emb.inv_freq
model.layers.2.mlp.gate_proj.weight
model.layers.2.mlp.down_proj.weight
model.layers.2.mlp.up_proj.weight
model.layers.2.input_layernorm.weight
model.layers.2.post_attention_layernorm.weight
model.layers.3.self_attn.q_proj.weight
model.layers.3.self_attn.k_proj.weight
model.layers.3.self_attn.v_proj.weight
model.layers.3.self_attn.o_proj.weight
model.layers.3.self_attn.rotary_emb.inv_freq
model.layers.3.mlp.gate_proj.weight
model.layers.3.mlp.down_proj.weight
model.layers.3.mlp.up_proj.weight
model.layers.3.input_layernorm.weight
model.layers.3.post_attention_layernorm.weight
model.layers.4.self_attn.q_proj.weight
model.layers.4.self_attn.k_proj.weight
model.layers.4.self_attn.v_proj.weight
model.layers.4.self_attn.o_proj.weight
model.layers.4.self_attn.rotary_emb.inv_freq
model.layers.4.mlp.gate_proj.weight
model.layers.4.mlp.down_proj.weight
model.layers.4.mlp.up_proj.weight
model.layers.4.input_layernorm.weight
model.layers.4.post_attention_layernorm.weight
model.layers.5.self_attn.q_proj.weight
model.layers.5.self_attn.k_proj.weight
model.layers.5.self_attn.v_proj.weight
model.layers.5.self_attn.o_proj.weight
model.layers.5.self_attn.rotary_emb.inv_freq
model.layers.5.mlp.gate_proj.weight
model.layers.5.mlp.down_proj.weight
model.layers.5.mlp.up_proj.weight
model.layers.5.input_layernorm.weight
model.layers.5.post_attention_layernorm.weight
model.layers.6.self_attn.q_proj.weight
model.layers.6.self_attn.k_proj.weight
model.layers.6.self_attn.v_proj.weight
model.layers.6.self_attn.o_proj.weight
model.layers.6.self_attn.rotary_emb.inv_freq
model.layers.6.mlp.gate_proj.weight
model.layers.6.mlp.down_proj.weight
model.layers.6.mlp.up_proj.weight
model.layers.6.input_layernorm.weight
model.layers.6.post_attention_layernorm.weight
model.layers.7.self_attn.q_proj.weight
model.layers.7.self_attn.k_proj.weight
model.layers.7.self_attn.v_proj.weight
model.layers.7.self_attn.o_proj.weight
model.layers.7.self_attn.rotary_emb.inv_freq
model.layers.7.mlp.gate_proj.weight
model.layers.7.mlp.down_proj.weight
model.layers.7.mlp.up_proj.weight
model.layers.7.input_layernorm.weight
model.layers.7.post_attention_layernorm.weight
model.layers.8.self_attn.q_proj.weight
model.layers.8.self_attn.k_proj.weight
model.layers.8.self_attn.v_proj.weight
model.layers.8.self_attn.o_proj.weight
model.layers.8.self_attn.rotary_emb.inv_freq
model.layers.8.mlp.gate_proj.weight
model.layers.8.mlp.down_proj.weight
model.layers.8.mlp.up_proj.weight
model.layers.8.input_layernorm.weight
model.layers.8.post_attention_layernorm.weight
model.layers.9.self_attn.q_proj.weight
model.layers.9.self_attn.k_proj.weight
model.layers.9.self_attn.v_proj.weight
model.layers.9.self_attn.o_proj.weight
model.layers.9.self_attn.rotary_emb.inv_freq
model.layers.9.mlp.gate_proj.weight
model.layers.9.mlp.down_proj.weight
model.layers.9.mlp.up_proj.weight
model.layers.9.input_layernorm.weight
model.layers.9.post_attention_layernorm.weight
model.layers.10.self_attn.q_proj.weight
model.layers.10.self_attn.k_proj.weight
model.layers.10.self_attn.v_proj.weight
model.layers.10.self_attn.o_proj.weight
model.layers.10.self_attn.rotary_emb.inv_freq
model.layers.10.mlp.gate_proj.weight
model.layers.10.mlp.down_proj.weight
model.layers.10.mlp.up_proj.weight
model.layers.10.input_layernorm.weight
model.layers.10.post_attention_layernorm.weight
model.layers.11.self_attn.q_proj.weight
model.layers.11.self_attn.k_proj.weight
model.layers.11.self_attn.v_proj.weight
model.layers.11.self_attn.o_proj.weight
model.layers.11.self_attn.rotary_emb.inv_freq
model.layers.11.mlp.gate_proj.weight
model.layers.11.mlp.down_proj.weight
model.layers.11.mlp.up_proj.weight
model.layers.11.input_layernorm.weight
model.layers.11.post_attention_layernorm.weight
model.layers.12.self_attn.q_proj.weight
model.layers.12.self_attn.k_proj.weight
model.layers.12.self_attn.v_proj.weight
model.layers.12.self_attn.o_proj.weight
model.layers.12.self_attn.rotary_emb.inv_freq
model.layers.12.mlp.gate_proj.weight
model.layers.12.mlp.down_proj.weight
model.layers.12.mlp.up_proj.weight
model.layers.12.input_layernorm.weight
model.layers.12.post_attention_layernorm.weight
model.layers.13.self_attn.q_proj.weight
model.layers.13.self_attn.k_proj.weight
model.layers.13.self_attn.v_proj.weight
model.layers.13.self_attn.o_proj.weight
model.layers.13.self_attn.rotary_emb.inv_freq
model.layers.13.mlp.gate_proj.weight
model.layers.13.mlp.down_proj.weight
model.layers.13.mlp.up_proj.weight
model.layers.13.input_layernorm.weight
model.layers.13.post_attention_layernorm.weight
model.layers.14.self_attn.q_proj.weight
model.layers.14.self_attn.k_proj.weight
model.layers.14.self_attn.v_proj.weight
model.layers.14.self_attn.o_proj.weight
model.layers.14.self_attn.rotary_emb.inv_freq
model.layers.14.mlp.gate_proj.weight
model.layers.14.mlp.down_proj.weight
model.layers.14.mlp.up_proj.weight
model.layers.14.input_layernorm.weight
model.layers.14.post_attention_layernorm.weight
model.layers.15.self_attn.q_proj.weight
model.layers.15.self_attn.k_proj.weight
model.layers.15.self_attn.v_proj.weight
model.layers.15.self_attn.o_proj.weight
model.layers.15.self_attn.rotary_emb.inv_freq
model.layers.15.mlp.gate_proj.weight
model.layers.15.mlp.down_proj.weight
model.layers.15.mlp.up_proj.weight
model.layers.15.input_layernorm.weight
model.layers.15.post_attention_layernorm.weight
model.layers.16.self_attn.q_proj.weight
model.layers.16.self_attn.k_proj.weight
model.layers.16.self_attn.v_proj.weight
model.layers.16.self_attn.o_proj.weight
model.layers.16.self_attn.rotary_emb.inv_freq
model.layers.16.mlp.gate_proj.weight
model.layers.16.mlp.down_proj.weight
model.layers.16.mlp.up_proj.weight
model.layers.16.input_layernorm.weight
model.layers.16.post_attention_layernorm.weight
model.layers.17.self_attn.q_proj.weight
model.layers.17.self_attn.k_proj.weight
model.layers.17.self_attn.v_proj.weight
model.layers.17.self_attn.o_proj.weight
model.layers.17.self_attn.rotary_emb.inv_freq
model.layers.17.mlp.gate_proj.weight
model.layers.17.mlp.down_proj.weight
model.layers.17.mlp.up_proj.weight
model.layers.17.input_layernorm.weight
model.layers.17.post_attention_layernorm.weight
model.layers.18.self_attn.q_proj.weight
model.layers.18.self_attn.k_proj.weight
model.layers.18.self_attn.v_proj.weight
model.layers.18.self_attn.o_proj.weight
model.layers.18.self_attn.rotary_emb.inv_freq
model.layers.18.mlp.gate_proj.weight
model.layers.18.mlp.down_proj.weight
model.layers.18.mlp.up_proj.weight
model.layers.18.input_layernorm.weight
model.layers.18.post_attention_layernorm.weight
model.layers.19.self_attn.q_proj.weight
model.layers.19.self_attn.k_proj.weight
model.layers.19.self_attn.v_proj.weight
model.layers.19.self_attn.o_proj.weight
model.layers.19.self_attn.rotary_emb.inv_freq
model.layers.19.mlp.gate_proj.weight
model.layers.19.mlp.down_proj.weight
model.layers.19.mlp.up_proj.weight
model.layers.19.input_layernorm.weight
model.layers.19.post_attention_layernorm.weight
model.layers.20.self_attn.q_proj.weight
model.layers.20.self_attn.k_proj.weight
model.layers.20.self_attn.v_proj.weight
model.layers.20.self_attn.o_proj.weight
model.layers.20.self_attn.rotary_emb.inv_freq
model.layers.20.mlp.gate_proj.weight
model.layers.20.mlp.down_proj.weight
model.layers.20.mlp.up_proj.weight
model.layers.20.input_layernorm.weight
model.layers.20.post_attention_layernorm.weight
model.layers.21.self_attn.q_proj.weight
model.layers.21.self_attn.k_proj.weight
model.layers.21.self_attn.v_proj.weight
model.layers.21.self_attn.o_proj.weight
model.layers.21.self_attn.rotary_emb.inv_freq
model.layers.21.mlp.gate_proj.weight
model.layers.21.mlp.down_proj.weight
model.layers.21.mlp.up_proj.weight
model.layers.21.input_layernorm.weight
model.layers.21.post_attention_layernorm.weight
model.layers.22.self_attn.q_proj.weight
model.layers.22.self_attn.k_proj.weight
model.layers.22.self_attn.v_proj.weight
model.layers.22.self_attn.o_proj.weight
model.layers.22.self_attn.rotary_emb.inv_freq
model.layers.22.mlp.gate_proj.weight
model.layers.22.mlp.down_proj.weight
model.layers.22.mlp.up_proj.weight
model.layers.22.input_layernorm.weight
model.layers.22.post_attention_layernorm.weight
model.layers.23.self_attn.q_proj.weight
model.layers.23.self_attn.k_proj.weight
model.layers.23.self_attn.v_proj.weight
model.layers.23.self_attn.o_proj.weight
model.layers.23.self_attn.rotary_emb.inv_freq
model.layers.23.mlp.gate_proj.weight
model.layers.23.mlp.down_proj.weight
model.layers.23.mlp.up_proj.weight
model.layers.23.input_layernorm.weight
model.layers.23.post_attention_layernorm.weight
```

**Comment by hiworldwzj** [comment]
@leiwen83 Hello. the weights name looks like ok. I download the weights from https://huggingface.co/jeffwan/llama-7b-hf, and it run ok in my env.  there are some other question in your env.  you can try：
~~~shell
# remove .triton cache
rm -rf ~/.triton 
# install triton == 2.1.0
pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly
~~~
this shell will change triton to 2.1.0 version, it have less bugs.  then try again.

**Comment by leiwen83** [comment]
With latest triton installed from master branch.

I got below error:
The cuTensorMapEncodeTiled seems only valid for device high than 9.0. While my machine is A100 40G, so maybe I need modify some config?

```
  File "/opt/lightllm/lightllm/models/llama/triton_kernel/rmsnorm.py", line 59, in rmsnorm_forward
    _rms_norm_fwd_fused[(M,)](x_arg, y, weight,
  File "<string>", line 77, in _rms_norm_fwd_fused
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/compiler/compiler.py", line 673, in __getattribute__
    self._init_handles()
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/compiler/compiler.py", line 649, in _init_handles
    driver.HIP: "hsaco_path",
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/runtime/driver.py", line 149, in __getattr__
    self._initialize_obj()
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/runtime/driver.py", line 146, in _initialize_obj
    self._obj = self._init_fn()
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/runtime/driver.py", line 178, in initialize_driver
    return CudaDriver()
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/runtime/driver.py", line 74, in __init__
    self.utils = CudaUtils()
  File "/opt/conda/lib/python3.9/site-packages/triton-2.1.0-py3.9-linux-x86_64.egg/triton/runtime/driver.py", line 51, in __init__
    mod = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /root/.triton/cache/c6a7b91a416b1ca1efa1318c10a89f87/cuda_utils.so: undefined symbol: cuTensorMapEncodeTiled
```

**Comment by leiwen83** [comment]
With commit [5df904233c11a65bd131ead7268f84cca7804275](https://github.com/openai/triton/commit/5df904233c11a65bd131ead7268f84cca7804275) , seem everything goes ok.
The latest H100 support broken the kernel as introduce new 9.0 API.
