### ISSUE TITLE
[BUG] parameter mismatch in llama/triton_kernal

### ISSUE THREAD

**Issue by bb-worm** [ModelTC/lightllm#208]
**Issue description:**
When I run lightllm server, I got an error `TypeError: token_att_fwd2() takes 7 positional arguments but 8 were given`.
My triton version is `2.0.0.dev20221202` and I'm using llama2 model.

[In function definition](https://github.com/ModelTC/lightllm/blob/59aee2904b173af587362a3470d1386c369b9470/lightllm/models/llama/triton_kernel/token_attention_nopad_reduceV.py#L49), parameter number is 7. But, 8 arguments are passed in [this code](https://github.com/ModelTC/lightllm/blob/59aee2904b173af587362a3470d1386c369b9470/lightllm/models/llama/layer_infer/transformer_layer_infer.py#L143C24-L143C24).

**Steps to reproduce:**

1. server: `python -m lightllm.server.api_server --model_dir {llama-2-7b-chat-hf} --tokenizer_mode auto --tp 1`
2. client: `curl http://127.0.0.1:8000/generate -X POST -d '{"inputs":"What is AI?", "parameters":{"max_new_tokens":17, "frequency_penalty":1}}' -H 'Content-Type: application/json'`
3. error: `TypeError: token_att_fwd2() takes 7 positional arguments but 8 were given`

**Error logging:**
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
Avg tokens(prompt+generate) throughput:    0.108 tokens/s
Avg prompt tokens throughput:              0.108 tokens/s
Avg generate tokens throughput:            0.000 tokens/s
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py:100> exception=TypeError('token_att_fwd2() takes 7 positional arguments but 8 were given')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 103, in loop_for_fwd
    await self._step()
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 147, in _step
    await self._decode_batch(self.running_batch)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 188, in _decode_batch
    ans = await asyncio.gather(*rets)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 284, in decode_batch
    ans = self._decode_batch(batch_id)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/utils/infer_utils.py", line 54, in inner_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 136, in exposed_decode_batch
    return self.forward(batch_id, is_prefill=False)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 186, in forward
    logits = self.model.forward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/common/basemodel/basemodel.py", line 143, in forward
    return self._decode(batch_size, total_token_num, max_len_in_batch, input_ids, b_req_idx, b_start_loc, b_seq_len)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/common/basemodel/basemodel.py", line 203, in _decode
    predict_logics = self._token_forward(input_ids, infer_state)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/common/basemodel/basemodel.py", line 220, in _token_forward
    input_embs = self.layers_infer[i].token_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_template.py", line 139, in token_forward
    self._token_attention(input_embdings,
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_template.py", line 112, in _token_attention
    o = self._token_attention_kernel(q, infer_state, layer_weight)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama/layer_infer/transformer_layer_infer.py", line 143, in _token_decode_attention_normal
    token_att_fwd2(prob,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: token_att_fwd2() takes 7 positional arguments but 8 were given
```

**Environment:**
- OS: (Ubuntu 20.04)
- GPU info:
  - `nvidia-smi` (`NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0`)
- Python: python3.10
- openai-triton: 2.0.0.dev20221202

**Comment by hiworldwzj** [comment]
@bb-worm thanks for your issue. the bug has been fixed in #210
