### ISSUE TITLE
llama2-70B 加载完成后，无法启动服务

### ISSUE THREAD

**Issue by zackdist** [ModelTC/lightllm#21]
机器 A100 80G *4
启动命令：python -m lightllm.server.api_server --model_dir /path_to/Llama-2-70b-hf --tp 4 --tokenizer_mode auto --max_total_token_num 512 
CUDA_V 11.7
python 3.8

模型权重加载卡住，每张卡上面大概30多G现存，然后就一直卡住了。一直起不来服务。

**Comment by hiworldwzj** [comment]
@zackdist  我会下载一个 70B的权重去复现一下，你可以用ctrl + c 去关闭程序一下，然后把打印的调用栈信息分享一下吗。我想观察下卡在什么地方了。

**Comment by hiworldwzj** [comment]
@zackdist  你可以尝试把python版本升级到3.9，这个问题就应该会消失。

**Comment by zackdist** [comment]
``
For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
^C

keyboard interrupt!
keyboard interrupt!
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 194, in _run_module_as_main

Process Process-1:
keyboard interrupt!

Process Process-2:
keyboard interrupt!
    return _run_code(code, main_globals, None,
  File ".../conda_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../conda_env/lib/python3.8/site-packages/lightllm-1.0.0-py3.8.egg/lightllm/server/api_server.py", line 160, in <module>
  File "<string>", line 7, in getvalue
KeyboardInterrupt
Traceback (most recent call last):
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File ".../conda_env/lib/python3.8/site-packages/lightllm-1.0.0-py3.8.egg/lightllm/server/detokenization/manager.py", line 70, in start_detokenization_process
    loop.run_until_complete(router.handle_loop())
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 213, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt
Traceback (most recent call last):
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File ".../conda_env/lib/python3.8/site-packages/lightllm-1.0.0-py3.8.egg/lightllm/server/router/manager.py", line 238, in start_router_process
    asyncio.run(router.wait_to_model_ready())
  File ".../conda_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File ".../conda_env/lib/python3.8/site-packages/lightllm-1.0.0-py3.8.egg/lightllm/server/router/manager.py", line 58, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)
  File "../conda_env/lib/python3.8/site-packages/lightllm-1.0.0-py3.8.egg/lightllm/server/router/model_infer/model_rpc.py", line 168, in init_model
    await asyncio.to_thread(ans.wait)
AttributeError: module 'asyncio' has no attribute 'to_thread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File ".../conda_env/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File ".../conda_env/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File ".../conda_env/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File ".../conda_env/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <function Socket.__del__ at 0x7fd3e857a310>
Traceback (most recent call last):
  File ".../conda_env/lib/python3.8/site-packages/zmq/sugar/socket.py", line 188, in __del__
  File ".../conda_env/lib/python3.8/site-packages/zmq/_future.py", line 243, in close
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Socket.__del__ at 0x7fd3e857a310>
Traceback (most recent call last):
  File ".../conda_env/lib/python3.8/site-packages/zmq/sugar/socket.py", line 188, in __del__
  File ".../conda_env/lib/python3.8/site-packages/zmq/_future.py", line 243, in close
TypeError: 'NoneType' object is not callable
``
报错信息如上

**Comment by zackdist** [comment]
> @zackdist 你可以尝试把python版本升级到3.9，这个问题就应该会消失。

好的 我尝试一下

**Comment by zackdist** [comment]
重新创建 3.9环境之后，安装依赖后，之后可以正常运行了~感谢

**Comment by hiworldwzj** [comment]
@zackdist 你最好拉取最新的代码，你设置的max_total_token_num 512 有点过于小了，在输入的问题长度比较长的时候可能会触发一个运行过程被卡住的bug，最新的代码已经修复，你可以试试。

**Comment by infwinston** [comment]
Python升級到3.9似乎還是遇到相同的問題，2xH800 load 70b模型 with --tp 2 會卡住，請問有什麼解法嗎？

**Comment by hb-jw** [comment]
> Python升級到3.9似乎還是遇到相同的問題，2xH800 load 70b模型 with --tp 2 會卡住，請問有什麼解法嗎？

同问，请问你解决了吗？
