### ISSUE TITLE
Baichuan2-13B-Chat not supported?

### ISSUE THREAD

**Issue by jarviszeng-zjc** [ModelTC/lightllm#223]
Baichuan2-7B-Chat是可以的，用的是最近的代码，我看到有commit记录说支持baichuan2-13B，难道还不支持chat版本？Baichuan2-13B-Chat报了如下的错误：
```bash
Traceback (most recent call last):
  File "/home/app/anaconda3/envs/lightllm/lib/python3.10/site-packages/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/app/anaconda3/envs/lightllm/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/data/jarviszeng/debug/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 116, in exposed_init_model
    raise e
  File "/data/jarviszeng/debug/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 93, in exposed_init_model
    self.model = Baichuan2_13bTpPartModel(model_kvargs)
  File "/data/jarviszeng/debug/lightllm/lightllm/models/baichuan2_13b/model.py", line 20, in __init__
    super().__init__(kvargs)
  File "/data/jarviszeng/debug/lightllm/lightllm/models/llama/model.py", line 31, in __init__
    super().__init__(kvargs)
  File "/data/jarviszeng/debug/lightllm/lightllm/common/basemodel/basemodel.py", line 44, in __init__
    self._init_weights()
  File "/data/jarviszeng/debug/lightllm/lightllm/models/llama/model.py", line 92, in _init_weights
    self.pre_post_weight.verify_load()
  File "/data/jarviszeng/debug/lightllm/lightllm/models/baichuan2_7b/layer_weights/pre_and_post_layer_weight.py", line 37, in verify_load
    weights = [self.wte_weight_, self.lm_head_weight_, self.final_norm_weight_]
AttributeError: 'Baichuan2_7bPreAndPostLayerWeight' object has no attribute 'wte_weight_'
```

**Comment by hiworldwzj** [comment]
@wxd000000

**Comment by wxd000000** [comment]
hi 你可能需要检查一下载入的Baichuan2-13B-Chat是不是完整。你的报错应该是源于载入的模型没有"model.embed_tokens.weight"。这层weight是用于把input_ids转换成embedding。
