### ISSUE TITLE
[BUG]Qwen72b  QWenTpPartModel object has no attribute max_ntk_alpha

### ISSUE THREAD

**Issue by ChristineSeven** [ModelTC/lightllm#302]
**Before you submit an issue, please search for existing issues to avoid duplicates.**

**Issue description:**

Task exception was never retrieved
future: <Task finished name='Task-8' coro=<RouterManager.loop_for_fwd() done, defined at /opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py:142> exception='QWenTpPartModel' object has no attribute 'max_ntk_alpha'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/conda/lib/python3.9/site-packages/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/utils/infer_utils.py", line 57, in inner_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 175, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 236, in forward
    logits = self.model.forward(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/common/basemodel/basemodel.py", line 148, in forward
    return self._prefill(batch_size, total_token_num, max_len_in_batch, input_ids, b_req_idx, b_start_loc, b_seq_len, multimodal_params)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/common/basemodel/basemodel.py", line 187, in _prefill
    infer_state.init_some_extra_state(self, input_ids)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/models/qwen/infer_struct.py", line 21, in init_some_extra_state
    infer_ntk_id = torch.clamp(torch.ceil(torch.log2(self.b_seq_len / model.config.get("seq_length", 2048)) + 1), 0, model.max_ntk_alpha).long()
AttributeError: 'QWenTpPartModel' object has no attribute 'max_ntk_alpha'

Please provide a clear and concise description of your issue.

**Steps to reproduce:**

Please list the steps to reproduce the issue, such as:

1. `command 0`
2. `command 2`
3. `command 3`

**Expected behavior:**

Please describe what you expected to happen.

**Error logging:**

If applicable, please copy and paste the error message or stack trace here. Use code blocks for better readability.

**Environment:**

Please provide information about your environment, such as:

- [ ] Using container

- OS: (Ubuntu 14.04, CentOS7)
- GPU info:
  - `nvidia-smi` (e.g. `NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0`)
  - Graphics cards: (e.g. 4090x8)
- Python: (e.g. CPython3.9)
  - currently, only python>=3.9 is supported
- LightLLm: (git commit-hash)
  - for container: `docker run --entrypoint cat --rm ghcr.io/modeltc/lightllm:main /lightllm/.git/refs/heads/main`
- openai-triton: `pip show triton`

**Additional context:**

Please add any other context or screenshots about the issue here.

**Language:**

Please use English as much as possible for better communication.

**Comment by hiworldwzj** [comment]
@ChristineSeven we will fix it soon.

**Comment by shihaobai** [comment]
@ChristineSeven We have fixed it: https://github.com/ModelTC/lightllm/commit/8ecd84da29b80d816e8df68db5738d9022e87edc
