### ISSUE TITLE
[BUG] test_llama.py error

### ISSUE THREAD

**Issue by Biubiubiu12** [ModelTC/lightllm#461]
`(slr_llm) root@NV4090:/home/liangrui.sheng/workspace/lightllm/test/model# python test_llama.py
INFO 07-10 10:37:14 [mem_utils.py:11] mode setting params: []
INFO 07-10 10:37:14 [mem_utils.py:23] Model kv cache using mode normal
Process Process-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/slr_llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/slr_llm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liangrui.sheng/workspace/lightllm/test/model/model_infer.py", line 52, in tppart_model_infer
    model_part = model_class(model_kvargs)
  File "/home/liangrui.sheng/workspace/lightllm/lightllm/models/llama/model.py", line 35, in __init__
    super().__init__(kvargs)
  File "/home/liangrui.sheng/workspace/lightllm/lightllm/common/basemodel/basemodel.py", line 59, in __init__
    self._init_mem_manager()
  File "/home/liangrui.sheng/workspace/lightllm/lightllm/models/llama/model.py", line 57, in _init_mem_manager
    self.mem_manager = select_mem_manager_class(self.mode)(self.max_total_token_num,
  File "/home/liangrui.sheng/workspace/lightllm/lightllm/common/mem_manager.py", line 24, in __init__
    assert nccl_port is not None
AssertionError

FAIL: test_llama_infer (__main__.TestLlamaInfer)

Traceback (most recent call last):
  File "/home/liangrui.sheng/workspace/lightllm/test/model/test_llama.py", line 13, in test_llama_infer
    test_model_inference(
  File "/home/liangrui.sheng/workspace/lightllm/test/model/model_infer.py", line 30, in test_model_inference
    assert not ans_queue.empty()
AssertionError

----------------------------------------------------------------------
Ran 1 test in 18.522s`

It can run normally through server.api_server, but the offline reasoning script reports an error
@hamelsmu @bingo787 @WuSiYu @

**Comment by hiworldwzj** [comment]
@Biubiubiu12 You should update your code to the latest code in the main branch. it will be ok.

**Comment by Biubiubiu12** [comment]
> @Biubiubiu12 You should update your code to the latest code in the main branch. it will be ok.

thanks, it work!
