### ISSUE TITLE
run error with baichuan-7B

### ISSUE THREAD

**Issue by HalFTeen** [ModelTC/lightllm#52]
my env:
OS=centos 7
GPU=1 * 3090 24G
python=3.10.12
baichuan-7B=https://huggingface.co/baichuan-inc/Baichuan-7B/tree/main
torch=1.13.0+cu117
cuda=cuda-11.8
triton=2.0.0.dev20221202
能启动，调用curl后报错：
```
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /data/wangjie/code/github/lightllm/lightllm/server/router/manager.py:83> exception=TypeError("mm(): argument 'mat2' (position 2) must be Tensor, not NoneType")>
Traceback (most recent call last):
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/manager.py", line 86, in loop_for_fwd
    await self._step()
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/manager.py", line 105, in _step
    await self._prefill_batch(self.running_batch)
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/manager.py", line 138, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 195, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/data/wangjie/code/github/lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 71, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/data/wangjie/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 122, in forward
    logits = self.model.forward(**kwargs)
  File "/data/wangjie/tools/miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/wangjie/code/github/lightllm/lightllm/models/llama/layer_infer/model.py", line 113, in forward
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/data/wangjie/code/github/lightllm/lightllm/models/llama/layer_infer/model.py", line 151, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/data/wangjie/code/github/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 117, in context_forward
    self._context_flash_attention(input_embdings,
  File "/data/wangjie/code/github/lightllm/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/data/wangjie/code/github/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 66, in _context_flash_attention
    q = torch.mm(input1.view(-1, self.embed_dim_), layer_weight.q_weight_)
TypeError: mm(): argument 'mat2' (position 2) must be Tensor, not NoneType
```
期待回复，谢谢

**Comment by llehtahw** [comment]
@HalFTeen 你可以检查一下权重文件里的权重名称，应该是因为权重没有加载上的问题，名称没有匹配上

**Comment by hiworldwzj** [comment]
@HalFTeen  Hello,  我发现 百川的 qkv矩阵乘矩阵是合并成一个大Tensor存储的，应该是这个地方出了问题， llama 本生是自己拆分成三个tensor存储的。导致了加载的时候没有加载 q，k, v 的转换矩阵。

**Comment by HalFTeen** [comment]
> @HalFTeen Hello, 我发现 百川的 qkv矩阵乘矩阵是合并成一个大Tensor存储的，应该是这个地方出了问题， llama 本生是自己拆分成三个tensor存储的。导致了加载的时候没有加载 q，k, v 的转换矩阵。

请问有什么详细的修改建议吗

**Comment by HalFTeen** [comment]
> @HalFTeen 你可以检查一下权重文件里的权重名称，应该是因为权重没有加载上的问题，名称没有匹配上

@llehtahw 我试了下，不是把名称换换那么简单，请问有交流群吗，issue总感觉时效性不够好 =.=

**Comment by XHPlus** [comment]
我们创建了个Discord服务器用于交流，欢迎在此交流：https://discord.gg/6gmf96UV。不过我们更加鼓励使用github来进行交流和贡献。

**Comment by HalFTeen** [comment]
> @HalFTeen Baichuan has been supported, code is #67, only test Baichuan-7B, you can try it.

yes it is! I have run the demo, thanks for your work, I'll try more test.
