### ISSUE TITLE
RuntimeError("Distributed package doesn't have NCCL " "built in")

### ISSUE THREAD

**Issue by shanekong** [ModelTC/lightllm#57]
I follow the instruction:
1.  setup env：
docker build -t image_name .
docker run -it --gpus all -p 8080:80 -v your_local_path:/data/ image_name /bin/bash

2. run model:
python -m lightllm.server.api_server --model_dir /path/llama-7B --tp 1 --max_total_token_num 120000

then meet the following exception:

Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:28765 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:28765 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:28765 (errno: 97 - Address family not supported by protocol).
Process Process-1:
Traceback (most recent call last):
  File "/storage03/users/kongxiangxing/projects/llm/llm_deploy/light_llm/lightllm/server/router/manager.py", line 243, in start_router_process
    asyncio.run(router.wait_to_model_ready())
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/storage03/users/kongxiangxing/projects/llm/llm_deploy/light_llm/lightllm/server/router/manager.py", line 57, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)
  File "/storage03/users/kongxiangxing/projects/llm/llm_deploy/light_llm/lightllm/server/router/model_infer/model_rpc.py", line 185, in init_model
    ans : rpyc.AsyncResult = self._init_model(rank_id, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/storage03/users/kongxiangxing/projects/llm/llm_deploy/light_llm/lightllm/server/router/model_infer/model_rpc.py", line 36, in exposed_init_model
    dist.init_process_group('nccl', init_method=f'tcp://127.0.0.1:{setting["nccl_port"]}', rank=rank_id, world_size=world_size)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/storage03/users/kongxiangxing/projects/llm/llm_deploy/light_llm/lightllm/server/router/manager.py", line 246, in start_router_process
    err_str = '\n'.join(traceback.format_exception(e))
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.

**Comment by hiworldwzj** [comment]
@llehtahw help help help

**Comment by songkq** [comment]
@shanekong conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by llehtahw** [comment]
@shanekong we've released the prebuilt docker image, and the build script is also modified. You can have a try. 

```
docker pull ghcr.io/modeltc/lightllm:main
```

**Comment by shanekong** [comment]
> @shanekong Conda Install Pytorch==2.0.0 Torchvision==0.15.0 Torchaudio==2.0.0 Pytorch-Cuda=11.8 -C Pytorch -C NVIDIA

ok, i will try it~ thanx!
