### ISSUE TITLE
ziya运行报错，求助

### ISSUE THREAD

**Issue by njhouse365** [ModelTC/lightllm#61]
/usr/bin/ld: skipping incompatible /usr/lib32/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib32/libcuda.so when searching for -lcuda
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /home/house365ai/xxm/lightllm/lightllm/server/router/manager.py:84> exception=CompilationError('at 38:4:\ndef _rotary_kernel(\n    Q, Cos, Sin,\n    stride_qbs, stride_qh, stride_qd,\n    stride_cosbs, stride_cosd,\n    stride_sinbs, stride_sind,\n    max_total_len,\n    H,  # N_CTX 代表要计算的上下文长度\n    BLOCK_HEAD: tl.constexpr,\n    BLOCK_SEQ: tl.constexpr,\n    BLOCK_DMODEL: tl.constexpr,\n):\n    cur_head_index = tl.program_id(0)\n    cur_seq_index = tl.program_id(1)\n\n    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)\n    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)\n\n    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)\n    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)\n\n    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd\n    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd\n\n    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd\n\n    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n\n    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n\n    out0 = q0 * cos - q1 * sin\n    out1 = q0 * sin + q1 * cos\n\n    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n\n    return\n    ^')>
Traceback (most recent call last):
  File "<string>", line 21, in _rotary_kernel
KeyError: ('2-.-0-.-0-d000bd1a52e8da5725b7d0d3a84e9be4-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-2d732a2488b7ed996facc3e641ee56bf-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (4, 32, 128), (True, True, True, (True, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (False, False), (False, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 937, in build_triton_ir
    generator.visit(fn.parse())
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 183, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 263, in visit_FunctionDef
    fn.reset_type(self.prototype.to_ir(self.builder))
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/language/core.py", line 298, in to_ir
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/language/core.py", line 298, in <listcomp>
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
AttributeError: 'NoneType' object has no attribute 'to_ir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 87, in loop_for_fwd
    await self._step()
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 106, in _step
    await self._prefill_batch(self.running_batch)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 139, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 182, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/home/house365ai/xxm/lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 67, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 118, in forward
    logits = self.model.forward(**kwargs)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/layer_infer/model.py", line 103, in forward
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/layer_infer/model.py", line 141, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 103, in context_forward
    self._context_flash_attention(input_embdings,
  File "/home/house365ai/xxm/lightllm/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 52, in _context_flash_attention
    rotary_emb_fwd(q.view(calcu_shape1), infer_state.position_cos, infer_state.position_sin)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/triton_kernel/rotary_emb.py", line 62, in rotary_emb_fwd
    _rotary_kernel[grid](
  File "<string>", line 41, in _rotary_kernel
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 1621, in compile
    next_module = compile(module)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 1550, in <lambda>
    lambda src: ast_to_ttir(src, signature, configs[0], constants)),
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 962, in ast_to_ttir
    mod, _ = build_triton_ir(fn, signature, specialization, constants)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 942, in build_triton_ir
    raise CompilationError(fn.src, node) from e
triton.compiler.CompilationError: at 38:4:
def _rotary_kernel(
    Q, Cos, Sin,
    stride_qbs, stride_qh, stride_qd,
    stride_cosbs, stride_cosd,
    stride_sinbs, stride_sind,
    max_total_len,
    H,  # N_CTX 代表要计算的上下文长度
    BLOCK_HEAD: tl.constexpr,
    BLOCK_SEQ: tl.constexpr,
    BLOCK_DMODEL: tl.constexpr,
):
    cur_head_index = tl.program_id(0)
    cur_seq_index = tl.program_id(1)

    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)
    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)

    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)
    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)

    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd
    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd

    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd

    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)
    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)

    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)
    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)

    out0 = q0 * cos - q1 * sin
    out1 = q0 * sin + q1 * cos

    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))
    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))

    return

**Comment by hiworldwzj** [comment]
@njhouse365  你检查一下你的环境和triton 环境和cuda版本，还有你这个是什么显卡，现在有些卡还不能很好的支持。还有你这个模型是什么模型，有些模型的权重名称可能没法兼容加载。

**Comment by llehtahw** [comment]
@njhouse365 检查 `triton==2.0.0.dev20221202`

**Comment by njhouse365** [comment]
我的2.0.0版本，模型是ziya-13b

**Comment by hiworldwzj** [comment]
@njhouse365  推荐使用这个版本 triton==2.0.0.dev20221202 ziya-13b 是 llama同架构的变种吗？

**Comment by njhouse365** [comment]
是的，支持量化模型吗？比如int8

**Comment by hiworldwzj** [comment]
@njhouse365 量化特性目前还没有实现，主要是还在实现比较快的 int8 weight only kernel， 后续会核心支持高性能的量化特性。

**Comment by njhouse365** [comment]
/usr/bin/ld: skipping incompatible /usr/lib32/libcuda.so when searching for -lcuda
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /home/house365ai/xxm/lightllm/lightllm/server/router/manager.py:84> exception=RuntimeError('unimplemented code: 34')>
Traceback (most recent call last):
  File "<string>", line 21, in _rms_norm_fwd_fused
KeyError: ('2-.-0-.-0-d000bd1a52e8da5725b7d0d3a84e9be4-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-f24b6aa9b101a518b6a4a6bddded372e-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'fp32'), (16384,), (True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 87, in loop_for_fwd
    await self._step()
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 106, in _step
    await self._prefill_batch(self.running_batch)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/manager.py", line 139, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 182, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/home/house365ai/xxm/lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 67, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/home/house365ai/xxm/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 118, in forward
    logits = self.model.forward(**kwargs)
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama2/layer_infer/model.py", line 105, in forward
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama2/layer_infer/model.py", line 143, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama2/layer_infer/transformer_layer_inference.py", line 111, in context_forward
    self._context_flash_attention(input_embdings,
  File "/home/house365ai/xxm/lightllm/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama2/layer_infer/transformer_layer_inference.py", line 57, in _context_flash_attention
    input1 = rmsnorm_forward(input_embding, weight=layer_weight.input_layernorm, eps=self.layer_norm_eps_)
  File "/home/house365ai/xxm/lightllm/lightllm/models/llama/triton_kernel/rmsnorm.py", line 59, in rmsnorm_forward
    _rms_norm_fwd_fused[(M,)](x_arg, y, weight,
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 41, in _rms_norm_fwd_fused
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/house365ai/.conda/envs/lightllm/lib/python3.9/site-packages/triton/compiler.py", line 901, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: unimplemented code: 34

**Comment by hiworldwzj** [comment]
@njhouse365 你可以说明一下你的硬件环境吗，显卡，cuda， python版本， triton版本。

**Comment by llehtahw** [comment]
https://github.com/openai/triton/blob/8650b4d1cbc750d659156e2c17a058736614827b/lib/driver/error.cc#L93
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html

> CUDA_ERROR_STUB_LIBRARY = 34
> This indicates that the CUDA driver that the application has loaded is a stub library. Applications that run with the stub rather than a real driver loaded will result in CUDA API returning this error.

https://github.com/ModelTC/lightllm/issues/16#issuecomment-1665536332

@njhouse365 检查你的cuda.so，避免在运行时load了stub里的cuda.so

**Comment by njhouse365** [comment]
{'generated_text': [' 山语��源��化��是30.5%。��化����确的提法应该为“��化������”，其����比������，可以说只要有草������的地方，都可以算作是��化面��。。</s>']}
{'generated_text': [' ����花语����的参����格是8500元/��。想要了解更����的��格信息，或房屋����可以��电4008908365转531！！</s>']}
{'generated_text': [' 中国��建青秀城交房时间是2017-12-31。。</s>']}
{'generated_text': [' 湖西��院在湖西��院位于建��区江东北路198号号</s>']}

**Comment by hiworldwzj** [comment]
@njhouse365  你是不是用得是老的代码，你用最新的代码试试，这个乱码问题已经修复了。

**Comment by njhouse365** [comment]
@hiworldwzj @llehtahw 可以，感谢指导!!!

**Comment by jemmyshin** [comment]
你好，我在RTX TITAN上也遇到了相同的问题，我跑的是LLAMA-1， 用的是 `triton==2.0.0.dev20221202`， cuda版本是11.6，python版本是3.10

**Comment by llehtahw** [comment]
> 你好，我在RTX TITAN上也遇到了相同的问题，我跑的是LLAMA-1， 用的是 `triton==2.0.0.dev20221202`， cuda版本是11.6，python版本是3.10

@jemmyshin 这个issue里有多个问题，不清楚你遇到的是哪个问题。

**Comment by jemmyshin** [comment]
<img width="821" alt="image" src="https://github.com/ModelTC/lightllm/assets/16580382/67c27db0-9326-4334-9b3e-0b4fc15d1774">
就是楼主碰到的这个问题

**Comment by jemmyshin** [comment]
我重新开一个新的issue吧
