### ISSUE TITLE
[BUG]Request using openai interface fails after startup

### ISSUE THREAD

**Issue by Dimensionzw** [ModelTC/lightllm#633]
## 1、appearance
Use lightllm to start the qwen2-7b service. When using the openai client to request, an error 1 validation error for ChatCompletionResponse is reported.
## 2、lightllm Version
3.0.0
## 3、server start command

```
python -m lightllm.server.api_server --model_dir /nlp/Qwen2-7B-instruct --trust_remote_code  --port 9000 --host 0.0.0.0
```

## 4、client code:

```
import base64
import time
import pdb
import requests

base64_str = cv2_base64(img_path)
url = "http://ip:9000/v1/chat/completions"

start_time = time.time()
payload = {
    "model": "default_model_name",
    "messages": [
        {
            "role": "user",
            "content": str("hello")
        }
    ],
    "repetition_penalty": 1.05,
    "temperature": 0.1,
    "top_p": 0.8,
    "top_k": 20,
    "max_tokens": 1
}
headers = {
    "content-type": "application/json"
}

response = requests.request("POST", url, json=payload, headers=headers)

print(response.text)
end = time.time()
infer_time = round((end - start_time)*1000, 3)
print("infer time is : {} ms".format(infer_time))
```
## 5、client error info:

```
Internal Server Error
infer time is : 313.196 ms
```

## 6、server error info:

```
INFO:     172.30.2.195:9361 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
DEBUG 12-02 09:36:21 [mem_manager.py:200] freed all gpu mem size 119308
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/conda/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/lightllm/lightllm/server/api_server.py", line 256, in chat_completions
    resp = ChatCompletionResponse(
  File "/opt/conda/lib/python3.9/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatCompletionResponse
id
  Input should be a valid string [type=string_type, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type

```
## 6、server start log

```
INFO 12-02 09:34:16 [cache_tensor_manager.py:17] USE_GPU_TENSOR_CACHE is On
/lightllm/lightllm/server/api_server.py:361: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("shutdown")
/lightllm/lightllm/server/api_server.py:380: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("startup")
INFO 12-02 09:34:17 [api_start.py:37] use tgi api: False
INFO 12-02 09:34:17 [api_start.py:145] all start args:Namespace(run_mode='normal', host='0.0.0.0', port=9000, pd_master_ip='127.0.0.1', pd_master_port=1212, pd_decode_rpyc_port=42000, model_name='default_model_name', model_dir='/opt/nfsdev220/serving/platform-modelhub/nlp/Qwen2-7B-instruct', tokenizer_mode='slow', load_way='HF', max_total_token_num=None, mem_fraction=0.9, batch_max_tokens=3072, eos_id=[151645], running_max_req_size=1000, tp=1, dp=1, max_req_total_len=3072, nccl_port=28765, mode=[], trust_remote_code=True, disable_log_stats=False, log_stats_interval=10, router_token_ratio=0.0, router_max_new_token_len=1024, router_max_wait_tokens=10, use_dynamic_prompt_cache=False, splitfuse_block_size=256, splitfuse_mode=False, beam_mode=False, diverse_mode=False, token_healing_mode=False, simple_constraint_mode=False, first_token_constraint_mode=False, enable_multimodal=False, cache_capacity=200, cache_reserved_ratio=0.5, data_type='bfloat16', return_all_prompt_logprobs=False, use_reward_model=False, long_truncation_mode=None, use_tgi_api=False, health_monitor=False, metric_gateway=None, job_name='lightllm', grouping_key=[], push_interval=10, visual_infer_batch_size=4, visual_gpu_ids=[0], visual_tp=1, visual_dp=1, visual_nccl_ports=[29500], enable_monitor_auth=False, disable_cudagraph=False, graph_max_batch_size=16, graph_max_len_in_batch=8192, quant_type=None, quant_cfg=None, pd_tp_infer_rpyc_ports=[10008], pd_node_id='b50ef4a8-eb1a-4591-857c-eca6e5c93bf5', pd_p_allowed_port_min=20000, pd_p_allowed_port_max=30000)
INFO 12-02 09:34:20 [cache_tensor_manager.py:17] USE_GPU_TENSOR_CACHE is On
INFO 12-02 09:34:21 [start_utils.py:29] init func start_metric_manager : init ok
INFO 12-02 09:34:21 [tokenizer.py:85] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 12-02 09:34:24 [cache_tensor_manager.py:17] USE_GPU_TENSOR_CACHE is On
INFO 12-02 09:34:24 [cache_tensor_manager.py:17] USE_GPU_TENSOR_CACHE is On
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_mem_manger_can_use_token_num_0
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_shared_token_load
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_shared_token_load_ext_infos
INFO 12-02 09:34:25 [model_rpc.py:79] use ContinuesBatchBackend
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_shared_token_load
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_shared_token_load_ext_infos
INFO 12-02 09:34:25 [shared_arr.py:21] link shm 28765_lock_tp_infos
INFO 12-02 09:34:25 [tokenizer.py:85] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 12-02 09:34:25 [basemodel.py:117] Initial quantization. The default quantization method is None
INFO 12-02 09:36:05 [mem_utils.py:11] mode setting params: []
INFO 12-02 09:36:05 [mem_utils.py:23] Model kv cache using mode normal
INFO 12-02 09:36:05 [mem_manager.py:61] 6.371734619140625 GB space is available after load the model weight
INFO 12-02 09:36:05 [mem_manager.py:61] 0.0546875 MB is the size of one token kv cache
INFO 12-02 09:36:05 [mem_manager.py:61] 119308 is the profiled max_total_token_num with the mem_fraction 0.9
INFO 12-02 09:36:05 [mem_manager.py:61] 
INFO 12-02 09:36:05 [mem_manager.py:33] mem manger get nccl port: 28765
INFO 12-02 09:36:05 [shared_arr.py:21] link shm 28765_mem_manger_can_use_token_num_0
INFO 12-02 09:36:05 [cuda_graph.py:51] Begin capture cudagraph, use the --disable_cudagraph to disable it.
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (16, 3584) torch.bfloat16 57344 57344
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 114688
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem torch.Size([16, 3584]) torch.bfloat16 57344 57344
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 229376
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (16, 3584) torch.bfloat16 57344 57344
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 344064
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (28, 131072) torch.float32 3670016 3670016
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 15024128
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (16, 37888) torch.bfloat16 606208 606208
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 16236544
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (16, 18944) torch.bfloat16 303104 303104
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 16842752
INFO 12-02 09:36:06 [cache_tensor_manager.py:92] pid 1080 cuda graph alloc mem (152064, 16) torch.bfloat16 2433024 2433024
INFO 12-02 09:36:06 [cache_tensor_manager.py:94] cuda graph managed_total_tensor_bytes: 21708800
INFO 12-02 09:36:06 [cache_tensor_manager.py:77] pid 1080 cuda graph alloc graph out mem (16, 152064) torch.float32 2433024 2433024
INFO 12-02 09:36:06 [cache_tensor_manager.py:83] cuda graph managed_total_tensor_bytes: 31440896
INFO 12-02 09:36:09 [cuda_graph.py:107] Capture cudagraph success, batch_size <=16 and max_len_in_batch <= 8192 will infer with cudagraph.
INFO 12-02 09:36:09 [basemodel.py:483] begin check max_len infer
INFO 12-02 09:36:09 [basemodel.py:511] check max_len 3072 infer ok
INFO 12-02 09:36:09 [base_backend.py:203] loaded model class <class 'lightllm.models.qwen2.model.Qwen2TpPartModel'>
INFO 12-02 09:36:09 [manager.py:151] use req queue ContinuesBatchQueue
INFO 12-02 09:36:09 [start_utils.py:29] init func start_router_process : init ok
INFO 12-02 09:36:09 [start_utils.py:29] init func start_detokenization_process : init ok
INFO 12-02 09:36:09 [shared_arr.py:21] link shm 28765_shared_token_load
INFO 12-02 09:36:09 [shared_arr.py:21] link shm 28765_shared_token_load_ext_infos
INFO:     Started server process [942]
INFO:     Waiting for application startup.
INFO 12-02 09:36:09 [api_server.py:382] server start up
INFO 12-02 09:36:09 [api_server.py:385] server start up ok
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO 12-02 09:36:21 [manager.py:184] recieved req X-Request-Id: X-Session-Id: start_time:2024-12-02 09:36:21 lightllm_req_id:0 
DEBUG 12-02 09:36:21 [manager.py:340] Init Batch: batch_id=f2ad71a59081423c8a9acf7c69f324e0, time:1733132181.5565255s req_ids:[0] 
DEBUG 12-02 09:36:21 [manager.py:340] 
DEBUG 12-02 09:36:21 [req_manager.py:28] freed all request size 1008
INFO 12-02 09:36:21 [manager.py:342] X-Request-Id: X-Session-Id: start_time:2024-12-02 09:36:21 lightllm_req_id:0 first_token_cost:145.2178955078125ms total_cost_time:145.25580406188965ms,out_token_counter:1 mean_per_token_cost_time: 0.03790855407714844ms prompt_token_num:449 prompt_cache_len:0 prompt_cache_ratio:0.0 

```

**Comment by hiworldwzj** [comment]
@Dimensionzw bug fixed.
