### ISSUE TITLE
[QUESTION] Is it expected to see an exception when running `benchmark_serving.py`

### ISSUE THREAD

**Issue by UranusSeven** [ModelTC/lightllm#90]
**Issue description:**

I was running benchmark_serving.py against llama2-7b:
```bash
$ python benchmark_serving.py --tokenizer /path/to/Llama-2-7b-chat-hf --dataset /path/to/ShareGPT_V3_unfiltered_cleaned_split.json
```

Outputs:
```python
Namespace(dataset='/path/to/ShareGPT_V3_unfiltered_cleaned_split.json', tokenizer='/path/to/Llama-2-7b-chat-hf', request_rate=inf, num_prompts=1000, seed=0)
read data set finish
total tokens: 494250
Traceback (most recent call last):
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 581, in write_bytes
    await self.body.write(writer)
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/payload.py", line 247, in write
    await writer.write(self._value)
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/http_writer.py", line 115, in write
    self._write(chunk)
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data/data_jon/repos/lightllm/test/benchmark_serving.py", line 236, in <module>
    main(args)
  File "/mnt/data/data_jon/repos/lightllm/test/benchmark_serving.py", line 198, in main
    asyncio.run(benchmark(input_requests, args.request_rate))
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/data/data_jon/repos/lightllm/test/benchmark_serving.py", line 187, in benchmark
    await asyncio.gather(*tasks)
  File "/mnt/data/data_jon/repos/lightllm/test/benchmark_serving.py", line 162, in send_request
    async with session.post(url, headers=headers, json=data) as response:
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/jon/data/miniconda3/envs/lightllm/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://localhost:8000/generate
```

The API server worked fine.

Please provide a clear and concise description of your issue.

**Steps to reproduce:**

Please list the steps to reproduce the issue, such as:

1. `command 0`
2. `command 2`
3. `command 3`

**Expected behavior:**

Please describe what you expected to happen.

**Error logging:**

If applicable, please copy and paste the error message or stack trace here. Use code blocks for better readability.

**Environment:**

Please provide information about your environment, such as:

- [ ] Using container

- OS: (Ubuntu 14.04, CentOS7)
- GPU info:
  - `nvidia-smi` (e.g. `NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0`)
  - Graphics cards: (e.g. 4090x8)
- Python: (e.g. CPython3.9)
  - currently, only python>=3.9 is supported
- LightLLm: (git commit-hash)
  - for container: `docker run --entrypoint cat --rm ghcr.io/modeltc/lightllm:main /lightllm/.git/refs/heads/main`
- openai-triton: `pip show triton`

**Additional context:**

Please add any other context or screenshots about the issue here.

**Language:**

Please use English as much as possible for better communication.

**Comment by hiworldwzj** [comment]
@UranusSeven  what is your port num that http server use ?

**Comment by UranusSeven** [comment]
The issue was found to be that the `request-rate` was set too high. I reproduced the benchmark results with `request-rate=20`:

LightLLM:

Total time: 201.07 s
Throughput: 9.95 requests/s
Average latency: 35.77 s
Average latency per token: 0.10 s
Average latency per output token: 0.48 s

vLLM:

Total time: 378.40 s
Throughput: 5.29 requests/s
Average latency: 118.56 s
Average latency per token: 0.39 s
Average latency per output token: 2.23 s
